# 5.1.4 [Challenge Project Euler](https://courses.thinkful.com/data-201v1/project/5.1.4)

In [1]:
import numpy as np

Now that you’ve learned a little bit about algorithms and written some really simple but essential code, it’s time to put those skills to the test. There is one resource above all that helps data scientists and other engineers practice their mathematical programming skills: [Project Euler](https://projecteuler.net/)

Project Euler is a fantastic set of mathematical programming problems. Use the skills we’ve discussed here to find efficient solutions to the first 10 problems. Once you’ve found your own solutions look around the web for others’ Python solutions to see other ways people have approached these problems.

It’s a good idea to come back to Project Euler and continue to work through these problems. They are a really great way to sharpen your mathematical programming.

**1. If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.**

In [17]:
num_list = []
for num in np.arange(1,1000):
    if num % 3 == 0:
        num_list.append(num)
    elif num % 5 == 0:
        num_list.append(num)

print(sum(num_list))

233168

**2. Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:**

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

**By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.**

In [34]:
# Create Fibonacci sequence

def create_fib(val_1, val_2):
    sequence = [1,2]

    for i in np.arange(1,10000):
        temp_val = val_1+val_2
        
        if temp_val <=4000000: 
            val_1 = val_2
            val_2 = temp_val
            if temp_val % 2 == 0:
                even_numbers.append(temp_val)
            sequence.append(temp_val)
    return sequence

fib = create_fib(1,2)

In [43]:
# Check to see if the value is even valued
even_numbers = []
for i in fib:
    if i % 2 == 0:
        even_numbers.append(i)
sum(even_numbers)

4613732

**3. The prime factors of 13195 are 5, 7, 13 and 29.**

**What is the largest prime factor of the number 600851475143?**

In [94]:
factor_list = []
def factors(n):
    while n > 1:
        for i in range(2, n+1):
            if n % i == 0:
                n = round(n/i) 
                yield i
                break

for factor in factors(600851475143):
    %time factor_list.append(factor)
print(factor_list)

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 6.2 µs
CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 5.96 µs
CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 6.2 µs
CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 6.2 µs
[71, 839, 1471, 6857]

**4. A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.**

Find the largest palindrome made from the product of two 3-digit numbers.

In [96]:
# We are looking for a 6 digit number that is the same front as backwords
999*999

998001

In [158]:
# check to see if a number is a palondrome

def palindrome_check(x):

    if x > 100000:
        temp = x
        temp = [int(d) for d in str(temp)]
        a = temp[:3]
        b = temp[3:]
        b.reverse()
        if a == b:
            palindrome_list.append(x)
    

palindrome_list = []
for i in range(10000, 998001):
    palindrome_check(i)

pals = []
divisor_1 = []
divisor_2 = []
for i in palindrome_list:
    for a in range(100,999):  
        if (i % a == 0) & (999>= i/a >= 100):
            b = i/a
            pals.append(i)
            divisor_1.append(a)
            divisor_2.append(b)
            
palindrome_dict = pd.DataFrame(
    data={'pals':pals, 'divisor_1':divisor_1, 'divisor_2':divisor_2}, 
    columns=['pals', 'divisor_1', 'divisor_2'])

palindrome_dict.sort_values(by='pals', ascending=False).head()

       pals  divisor_1  divisor_2
976  906609        993      913.0
975  906609        913      993.0
974  888888        962      924.0
973  888888        924      962.0
972  886688        968      916.0

**5. 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.**

**What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?**

In [193]:
for a in np.arange(17907120, 200000000, 20):    
    n = 0
    for i in range(1,21):
        if a % i == 0:
            n += 1
            if n == 20:
                print(a)

KeyboardInterrupt:

**6. Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.**

**Sum of the squares of the first ten natural numbers is:**

1^2 + 2^2 + ... + 10^2 = 385

**The square of the sum of the first ten natural numbers is**

(1 + 2 + ... + 10)^2 = 552^2 = 3025

**The difference between the sum of the squares of the first ten natural numbers and the square of the sum is:** 

3025 − 385 = 2640

In [202]:
def dif_squares(x):    
    n = 0 
    for i in range(1,x+1):
        n += (i**2)

    z = 0
    for i in range(1,x+1):
        z += i
    z = z**2
    return z - n

print(dif_squares(100))

25164150

**7. By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.**

What is the 10 001st prime number?

In [254]:
x = 0 
primes = []

for n in range(2,1000000):
    isPrime = True
    for num in range(2, n):
        if n % num ==0:
                isPrime = False
                break
    if isPrime:
        primes.append(n)
    
    if len(primes) >= 10001:
        break
print(primes[-2:])
print(len(primes))

[104729, 104743]
10001

**The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.**

73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450

**Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?**

In [264]:
long = 731671765313306249192251196744265\
74742355349194934969835203127745063262395\
78318016984801869478851843858615607891129\
494954595017379583319528532088055111254069\
8747158523863050715693290963295227443043557\
6689664895044524452316173185640309871112172\
2383113622298934233803081353362766142828064\
44486645238749303589072962904915604407723907\
13810515859307960866701724271218839987979087\
92274921901699720888093776657273330010533678\
81220235421809751254540594752243525849077116\
70556013604839586446706324415722155397536978\
17977846174064955149290862569321978468622482\
83972241375657056057490261407972968652414535\
10047482166370484403199890008895243450658541\
22758866688116427171479924442928230863465674\
81391912316282458617866458359124566529476545\
68284891288314260769004224219022671055626321\
11110937054421750694165896040807198403850962\
45544436298123098787992724428490918884580156\
16609791913387549920052406368991256071760605\
88611646710940507754100225698315520005593572\
97257163626956188267042825248360082325753042\
0752963450
long_list = [int(d) for d in str(long)]

In [332]:
product = []
for g in np.arange(0,len(long_list)-13):
    n = long_list[g]
    for x in np.arange(g+1,g+13): 
        n = long_list[x]*n
    product.append(n)
print(np.max(product))

23514624000

**8. A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,**

a2 + b2 = c2
For example, 32 + 42 = 9 + 16 = 25 = 52.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

In [341]:
a_list = []
b_list = []
c_list = []
sum_list = []
for a in range(1,1000):
    for b in range(1,1000):
        for c in range(1,1000):
            if a**2 + b**2 == c**2:
                a_list.append(a)
                b_list.append(b)
                c_list.append(c)
                sum_list.append((a+b+c))
pythag_data = pd.DataFrame(data={'a_list':a_list, 'b_list':b_list, 
                   'c_list':c_list, 'sum_list':sum_list},
             columns = ['a_list', 'b_list', 'c_list', 'sum_list'])

In [346]:
pythag_data[pythag_data['sum_list']==1000]

      a_list  b_list  c_list  sum_list   product
578      200     375     425      1000  31875000
1013     375     200     425      1000  31875000

In [345]:
pythag_data['product']=pythag_data['a_list']*pythag_data['b_list']*pythag_data['c_list']

**9. The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.**

Find the sum of all the primes below two million.

In [6]:
x = 0 
primes = []

def isPrime(n):
    for i in range(2, int(n**0.5) +1):
        if n % i == 0:
            return False
    return True
    
for i in range(2, 2000000):
    if isPrime(i):
        x += i
        primes.append(i)  
print(x)
print(sum(primes))

142913828922
142913828922